CREATE TABLE ATL_Pessoa(
    N_CC int NOT NULL PRIMARY KEY,
    Data_nascimento DATE NOT NULL, Morada VARCHAR(1024) NOT NULL, Telefone VARCHAR(15) NOT NULL, Nome VARCHAR(256) NOT NULL, Email VARCHAR(256) NOT NULL, Parentesco VARCHAR(256)
);
GO